aws:
  accessKeyId: ${}
  secretKey: ${}
spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: YOUR_COGNITO_CLIENT_ID
            client-secret: YOUR_COGNITO_CLIENT_SECRET
        provider:
          cognito:
            issuer-uri: https://cognito-idp.{region}.amazonaws.com/{userPoolId}
